In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [2]:
import numpy as np

In [4]:
from sklearn.datasets import load_digits

digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size = 0.3)

In [6]:
len(X_train)

1257

In [7]:
len(X_test)

540

In [8]:
sv = SVC()
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.9851851851851852

In [9]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/Users/balarusum/opt/anaconda3/envs/tensor-env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [11]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt.score(X_test,y_test)

0.8518518518518519

In [12]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9592592592592593

In [16]:
from sklearn.model_selection import KFold

kf = KFold(n_splits= 4)

In [17]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [18]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    
    return model.score(X_test,y_test)


In [19]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits = 3)

In [22]:
scores_lr = []
scores_svm = []
scores_rf = []

In [24]:
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index] , digits.data[test_index] , digits.target[train_index], digits.target[test_index]
    
    scores_lr.append(get_score(LogisticRegression(), X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(), X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train,X_test,y_train,y_test))

/Users/balarusum/opt/anaconda3/envs/tensor-env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/balarusum/opt/anaconda3/envs/tensor-env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.

In [25]:
scores_lr

[0.9355555555555556,
 0.9355555555555556,
 0.9153674832962138,
 0.9510022271714922,
 0.9175946547884187]

In [26]:
scores_svm

[0.9644444444444444,
 0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [27]:
scores_rf

[0.9422222222222222,
 0.9220489977728286,
 0.9755011135857461,
 0.9398663697104677]

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data,digits.target)

/Users/balarusum/opt/anaconda3/envs/tensor-env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/balarusum/opt/anaconda3/envs/tensor-env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [29]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [30]:
cross_val_score(RandomForestClassifier(), digits.data,digits.target)

array([0.93611111, 0.91111111, 0.95821727, 0.96935933, 0.91643454])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators= 30), digits.data,digits.target)

array([0.93333333, 0.88055556, 0.94428969, 0.96100279, 0.90807799])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators= 40), digits.data,digits.target)

array([0.925     , 0.91111111, 0.96657382, 0.96935933, 0.92200557])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators= 50), digits.data,digits.target)

array([0.92777778, 0.88888889, 0.95821727, 0.96935933, 0.92200557])