# List to Numpy array

In [1]:
list_l = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
np.array(list_l)

array([1, 2, 3, 4])

List stores all types of data, where as numpy stores same type

In [4]:
list_l1 = [1,2,3,'a','b','c']

In [5]:
np.array(list_l1)

array(['1', '2', '3', 'a', 'b', 'c'], dtype='<U21')

# Nested list to 2D numpy array

In [7]:
mat = [[1,2,3,4],[5,6,7,8]]
mat

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
np.array(mat)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(mat1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np arange with start and end

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# np arrange with step size

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(2)

array([0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [17]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# rand uses uniform distribution

In [21]:
np.random.rand(3)

array([0.71033708, 0.58550885, 0.60794083])

# randn uses standard normal distribution

In [22]:
np.random.randn(3)

array([-1.22568757, -0.35581612, -0.45044922])