In [37]:
import numpy as np


In [38]:
arr1 = np.array([2,3,6,8])
arr1

array([2, 3, 6, 8])

In [39]:
arr2 = np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr2.ndim

2

In [6]:
arr3 = np.ones((3,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr4 = np.arange(0,10,2)
arr4

array([0, 2, 4, 6, 8])

In [8]:
arr5 = np.linspace(0,1,5)
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr6.size

9

In [11]:
arr6.shape

(3, 3)

In [14]:
arr7 = np.array([[1,3,5],[3,5,7]], dtype = np.float64)

In [17]:
arr7.dtype

dtype('float64')

In [18]:
arr7.shape

(2, 3)

In [19]:
arr7.reshape(3,2) #reshaping the original (2,3) array to (3,2)

array([[1., 3.],
       [5., 3.],
       [5., 7.]])

In [20]:
arr7.ravel() #flatten the given array

array([1., 3., 5., 3., 5., 7.])

In [21]:
arr7 #the original array is untouched with ravel()

array([[1., 3., 5.],
       [3., 5., 7.]])

In [22]:
arr7.min() #minimum value in the array

1.0

In [23]:
arr7.max() #maximun value in the array

7.0

In [24]:
arr7.sum() #sum all the array elements 

24.0

In [25]:
arr7.sum(axis = 0) #sum of rows

array([ 4.,  8., 12.])

In [26]:
arr7.sum(axis = 1) #sum of columns

array([ 9., 15.])

In [28]:
np.sqrt(arr7) #square root of all the elements in an array

array([[1.        , 1.73205081, 2.23606798],
       [1.73205081, 2.23606798, 2.64575131]])

In [29]:
arr7

array([[1., 3., 5.],
       [3., 5., 7.]])

In [30]:
np.std(arr7) #standard deviation of all the elements in array

1.9148542155126762

In [32]:
a = np.array([[2,3],[4,6]])
b = np.array([[2,5],[3,0]])

In [33]:
a + b #adding two numpy arrays

array([[4, 8],
       [7, 6]])

In [34]:
a * b #multiplying two numpy arrays

array([[ 4, 15],
       [12,  0]])

In [35]:
a / b #dividing two numpy arrays

/var/folders/db/y2f9wrld6q5214f91hwssy880000gn/T/ipykernel_63593/1286629031.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[1.        , 0.6       ],
       [1.33333333,        inf]])

In [36]:
a.dot(b) #dot product

array([[13, 10],
       [26, 20]])